[projects.test]
path = "C:\\Users\\devco\\OneDrive\\Pictures\\Screenshots 1\\New folder"
name = "test"
engine_version = "1.9.0"
icon = "C:\\Users\\devco\\OneDrive\\Pictures\\Roblox\\6039379308_71732527189623_1729073781157.png"
last_opened = 1771436933
