[projects.fart]
path = "C:\\Users\\devco\\Downloads\\win-x64"
name = "fart"
engine_version = "1.9.0"
icon = "C:\\Users\\devco\\Downloads\\api_24dp_E3E3E3_FILL1_wght400_GRAD-25_opsz24.png"
last_opened = 1772712456
